// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreManagement.Data;

namespace StoreManagement.Migrations
{
    [DbContext(typeof(StoreManagementDbContext))]
    [Migration("20210522193254_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("StoreManagement.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cargo")
                        .HasColumnType("longtext");

                    b.Property<string>("Cpf")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Endereco")
                        .HasColumnType("longtext");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Funcionarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cargo = "Global Applications Specialist",
                            Cpf = "551.825.468-74",
                            Email = "Ofelia.Martins24@yahoo.com",
                            Endereco = "83539 Júlio César Avenida, Campinas, Eslováquia",
                            Idade = 38,
                            Nome = "Janaína Moraes",
                            Telefone = "(68) 28528-5659"
                        },
                        new
                        {
                            Id = 2,
                            Cargo = "Dynamic Web Developer",
                            Cpf = "704.593.351-70",
                            Email = "Fabricio_Xavier6@yahoo.com",
                            Endereco = "44530 Lorena Marginal, Londrina, Samoa",
                            Idade = 41,
                            Nome = "Ofélia Batista",
                            Telefone = "(27) 80628-0915"
                        },
                        new
                        {
                            Id = 3,
                            Cargo = "Legacy Functionality Supervisor",
                            Cpf = "887.613.340-22",
                            Email = "MariaAlice68@hotmail.com",
                            Endereco = "556 Santos Avenida, São Luís, Dominica",
                            Idade = 18,
                            Nome = "Roberta Costa",
                            Telefone = "(43) 42400-6750"
                        },
                        new
                        {
                            Id = 4,
                            Cargo = "Legacy Metrics Coordinator",
                            Cpf = "232.680.457-07",
                            Email = "Heitor76@gmail.com",
                            Endereco = "113 Yuri Rua, Betim, Suíça",
                            Idade = 40,
                            Nome = "Dalila Nogueira",
                            Telefone = "(80) 86925-7941"
                        },
                        new
                        {
                            Id = 5,
                            Cargo = "Internal Research Administrator",
                            Cpf = "970.408.133-27",
                            Email = "Carlos82@bol.com.br",
                            Endereco = "0777 Batista Marginal, Contagem, Iraque",
                            Idade = 41,
                            Nome = "Melissa Costa",
                            Telefone = "(18) 67488-4366"
                        });
                });

            modelBuilder.Entity("StoreManagement.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Categoria")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = "Industrial",
                            Nome = "Pequeno Fresco Bacon",
                            Preco = 834.44m,
                            Quantidade = 80
                        },
                        new
                        {
                            Id = 2,
                            Categoria = "Mercearia & Ferramentas",
                            Nome = "Sem marca Aço Mesa",
                            Preco = 332.69m,
                            Quantidade = 11
                        },
                        new
                        {
                            Id = 3,
                            Categoria = "Sapatos",
                            Nome = "Prático Fresco Calças",
                            Preco = 758.09m,
                            Quantidade = 62
                        },
                        new
                        {
                            Id = 4,
                            Categoria = "Casa, Roupas & Eletrônicos",
                            Nome = "Lindo Granito Cadeira",
                            Preco = 616.31m,
                            Quantidade = 11
                        },
                        new
                        {
                            Id = 5,
                            Categoria = "Automotivo, Turismo & Casa",
                            Nome = "Sem marca Congelado Mouse",
                            Preco = 283.25m,
                            Quantidade = 36
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
